# =====================================
# 💾 WORKFLOW.yaml
# =====================================
#
# 【このファイルの役割】
# プロジェクトの進捗状況・決定事項・ファイル構成を記録するセーブデータ。
# プロジェクトの「今どうなっているか」を保存する。頻繁に更新される動的な情報。
# このファイルをAIに渡すことで、前回の続きから開発を再開できる。
#
# 【このファイルに書くこと】
# - 実装中・計画中の機能とステータス（planned / in_progress）
# - 採用した決定事項（なぜその実装方法を選んだか）
# - 保留中の決定事項（後で検討する予定のもの）
# - 現在の進捗（今どのフェーズか、次に何をやるか）
# - ファイル構成（どのファイルが何の役割か、依存関係）
# - 開発中に発見した注意点・ハマったこと
# - 将来の拡張候補（いつか追加するかもしれない設定等）
# - 運用データ（業態一覧など、DBの現状を反映したもの）
#
# 【このファイルに書かないこと】
# - 実装済み機能の仕様 → ARCHITECTURE.yaml
# - AIの振る舞いやルール → SYSTEM_PROMPT.yaml
# - 開発プロセスの定義 → SYSTEM_PROMPT.yaml
# - プロジェクト固有の設定・仕様 → PROJECT_SPECIFIC.yaml
# - 技術スタック・環境情報 → PROJECT_SPECIFIC.yaml
# - テーブル定義・カラム情報 → DATABASE.md
# - SQLやマイグレーション履歴 → DATABASE.md
#
# 【このファイルを更新するタイミング】
# - 機能の実装が完了したとき → ARCHITECTURE.yamlに移動し、ここから削除
# - 新しい機能を追加することが決まったとき → features に追加
# - 実装方法を決定したとき → decisions.adopted に追加
# - 後で検討することにしたとき → decisions.postponed に追加
# - 新しいファイルを作成したとき → file_structure に追加
# - ハマったこと・注意点を発見したとき → cautions に追加
# - セッション終了時 → last_updated と last_session_summary を更新
# - 業態を追加・変更したとき → current_data.business_types を更新
#
# 【セクション構成】
# 1. 実装中・計画中の機能
# 2. 決定事項の記録
# 3. 現在の進捗
# 4. ファイル構成
# 5. 注意点・ハマったこと
#
# 【重要】
# ⚠️ ここに書かれていない進捗・決定事項はプロジェクトから消える
# ⚠️ git push前に必ずこのファイルを更新すること
# ⚠️ セッション終了時にAIが更新版を出力するので保存すること
# ⚠️ AIはプロジェクト内のコード内容を全て理解した上で作業を進めること
# ⚠️ 機能が完了したらARCHITECTURE.yamlに移動すること
#
# =====================================

workflow:
  version: "4.4"
  last_updated: "2026-01-04"
  last_session_summary: |
    F022（AIサポート機能）とF027（モーダル共通化）の動作確認完了！🎉
    
    【完了した機能】
    - F022: AIサポート機能（全7ステップ）
    - F023: セッション自動保存・復元
    - F024: AI検索カテゴリ見出し改善
    - F025: 「自分で探す」改善
    - F026: 仕入れ商品なしアイテム（手動単価）
    - F027: モーダル共通化リファクタリング
    
    【動作確認結果】
    - preparations.html: クイックアイテム作成OK
    - dishes.html: クイックアイテム作成OK
    - ai-support.html: 全フロー（STEP1〜7）OK
    
    【次回リスタート時のポイント】
    - 実装中・計画中の機能なし
    - 新しい機能の要望があれば対応
    - PPT/Excel対応は保留中（P011）

  # =====================================
  # 1. 実装中・計画中の機能
  # =====================================
  features:
    in_progress: []
    planned: []

  # =====================================
  # 2. 決定事項の記録
  # =====================================
  decisions:
    adopted:
      # --- AIサポート機能（F022） ---
      - id: "D079"
        idea: "AIサポート機能は専用ページで実装"
        reason: "既存ページを壊したくない"
      - id: "D080"
        idea: "AIサポートのメニュー配置はマスタ管理の上"
        reason: "閲覧系と管理系の間"
      - id: "D081"
        idea: "AI APIはGemini 2.5 Flashを採用"
        reason: "最新モデル、応答スピード最速、画像読み取り対応、料金安い、精度十分"
      - id: "D082"
        idea: "AI APIはSupabase Edge Functions経由で呼び出す"
        reason: "APIキーをフロントに露出しない、セキュリティ確保"
      - id: "D083"
        idea: "AIサポートのフローは7ステップ"
        details: "アップロード→レシピ選択→種別+基本情報→材料確認→紐付け→分量確認→完了"
      - id: "D084"
        idea: "材料の紐付けは1個ずつモーダルで行う"
        reason: "集中できる、シンプル"
      - id: "D085"
        idea: "紐付けモーダルはテンプレート固定、AIはデータだけ返す"
        reason: "毎回モーダル生成せず効率的"
      - id: "D086"
        idea: "紐付け画面は「🤖 AIで探す」「🔍 自分で探す」の2ボタン方式"
        reason: "AIが見つけられない場合も手動で対応可能"
      - id: "D087"
        idea: "AIの検索キーワード生成は短いワード複数（2〜5文字）"
        reason: "部分一致検索でヒット率を上げるため"
      - id: "D088"
        idea: "AIが類義語・表記ゆれを推測して検索"
        reason: "辞書不要、柔軟に対応できる"
      - id: "D089"
        idea: "登録済みレシピは警告表示するが続行可能"
        reason: "同じ名前でも業態やアレンジ違いの可能性があるため"
      - id: "D090"
        idea: "分量・単位の確認は紐付け後にまとめて行う"
        reason: "紐付けと分量調整を分離、全体を見ながら調整できる"
      - id: "D091"
        idea: "基本情報（名前・読み仮名・セクション等）はSTEP3で入力"
        reason: "種別選択と同時に入力、AIが初期値をセット"
      - id: "D092"
        idea: "登録完了後は未登録レシピリストを表示して続行可能"
        reason: "連続で複数レシピを登録しやすい"
      - id: "D093"
        idea: "AIサポートの対応ファイル形式は画像とPDFを先行、PPT/Excelは後回し"
        reason: "Gemini APIがPPT/Excelを直接読めないため、テキスト抽出が必要"
      - id: "D094"
        idea: "AI検索（ai-search-keywords）は仮実装で先に進む"
        reason: "基本フローを動かすことを優先"
      - id: "D095"
        idea: "STEP2でレシピ選択後、goToStep(2)時にrenderRecipeList()を呼び出す"
        reason: "2回目以降の登録時に表示とクリック内容がズレる問題を修正"
      - id: "D096"
        idea: "登録済みチェックはAI一括判定（ai-check-duplicates Edge Function）"
        reason: "空振りOK、見逃しNGの方針で緩めに判定"
      - id: "D097"
        idea: "類似判定は仕込み品+商品の両方をチェック（現在の業態のみ）"
        reason: "重複登録を防ぐため"
      - id: "D098"
        idea: "類似候補は1レシピに対して複数表示可能"
        reason: "複数の候補がヒットするケースに対応"
      - id: "D099"
        idea: "類似候補は⚠️ホバーでツールチップ表示（レシピ名の横に配置）"
        reason: "一覧の見やすさを保ちつつ詳細を確認可能"
      - id: "D100"
        idea: "レシピ一覧に🗑️削除アイコンを追加"
        reason: "ユーザーが重複と判断したものをリストから削除できる"
      - id: "D101"
        idea: "STEP3のバリデーションは必須項目を全てチェック（種別、名前、読み仮名、セクション）"
        reason: "STEP4に進む前に確実に入力させる"
      - id: "D102"
        idea: "仕上がり量・仕上がり単位はSTEP6で入力"
        reason: "分量確認と一緒に入力する方が自然"
      - id: "D103"
        idea: "ai-search-keywords Edge Functionでキーワード+読み仮名を生成"
        reason: "1回のAPI呼び出しで両方取得、追加コストなし"
      - id: "D104"
        idea: "AIで探す時の検索結果は一括表示（アイテム/仕込み品/仕入れをセクション分け）"
        reason: "タブ切り替えより一覧性が高い"
      - id: "D105"
        idea: "「自分で探す」時は検索欄に材料名をデフォルトセット"
        reason: "すぐ検索できる、ヒットしなければユーザーが修正"
      - id: "D106"
        idea: "クイックアイテム作成時はアイテム名=材料名、読み仮名=AI生成値をデフォルトセット"
        reason: "入力の手間を減らす"
      - id: "D107"
        idea: "リロード機能：読み取り結果をDBに自動保存"
        reason: "ページリロードしても続きから再開できる"
      - id: "D108"
        idea: "セッション保存はステップ移動のたびに自動実行"
        reason: "保存し忘れがない、DB負荷も問題なし"
      - id: "D109"
        idea: "セッションは業態単位で直近10件保存"
        reason: "業態ごとに履歴が分かれる、十分な件数"
      - id: "D110"
        idea: "11件目作成時に最も古いセッションを自動削除"
        reason: "シンプル、常に10件以内を保証"
      - id: "D111"
        idea: "履歴一覧はSTEP1のファイルアップロード下に表示"
        reason: "最初にアクセスしたとき目に入る、自然な導線"
      - id: "D112"
        idea: "履歴一覧の表示項目：ファイル名 + 日時（残り◯件）"
        reason: "シンプルで十分な情報"
      - id: "D113"
        idea: "セッションの手動削除機能あり（🗑️ボタン）"
        reason: "不要なセッションを消したいケースがある"
      - id: "D114"
        idea: "AI検索結果のカテゴリ見出しは全幅帯・背景色・中央揃え太字"
        reason: "どのカテゴリを見てるかわかりやすい"
      - id: "D115"
        idea: "カテゴリ色分け：アイテム=青、仕込み品=オレンジ、仕入れ商品=緑"
        reason: "直感的に区別できる"
      - id: "D116"
        idea: "0件のカテゴリも見出しを表示（該当なしと表示）"
        reason: "全カテゴリ検索したことがわかる"
      - id: "D117"
        idea: "「自分で探す」クリック時に検索窓に材料名セット+自動検索"
        reason: "すぐ候補が見える、ワンアクション減る"

      # --- F026: 仕入れ商品なしアイテム ---
      - id: "D118"
        idea: "仕入れ商品なしアイテムを許可（手動単価入力）"
        reason: "仕入れ商品がない材料も登録できる"
      - id: "D119"
        idea: "手動単価アイテムは manual_price=true フラグで管理"
        reason: "通常アイテムと区別、一覧で確認できる"
      - id: "D120"
        idea: "手動単価アイテムは🔁マークで表示（編集ページのみ）"
        reason: "⚠️（要確認）と区別、原価手動更新を示す"
      - id: "D121"
        idea: "「仕入れ商品なしで作成」ボタンは仕入れ商品タブ内、検索窓の下に配置"
        reason: "タブを増やさずシンプル、目立つ位置"
      - id: "D122"
        idea: "手動単価入力は「総量・単位・仕入れ金額」で単位原価を自動計算"
        reason: "いきなり単位原価を入力するのは難しい、金額0円も許可"

      # --- F027: モーダル共通化リファクタリング ---
      - id: "D123"
        idea: "QuickItemModalManagerのHTMLを動的生成に変更"
        reason: "各ページからモーダルHTMLを削除し、modalManagers.jsで一元管理。変更時に1箇所直せばOK"
      - id: "D124"
        idea: "モーダル共通化リファクタリングは要件定義から丁寧に進める"
        reason: "影響範囲が大きいため、まず全体把握してから段階的に進める"
      - id: "D125"
        idea: "utils.js と modalManagers.js にファイル分割"
        reason: "責務を明確に分離。utils.js=汎用ユーティリティ、modalManagers.js=モーダル管理クラス"
      - id: "D126"
        idea: "QuickItemModalManager.open() は HTMLElement と Object 両方に対応"
        reason: "preparations.js/dishes.jsはDOM要素、ai-support.jsはオブジェクトを渡すため"

    postponed:
      - id: "P001"
        idea: "歩留率の導入"
        trigger: "必要になったら"
      - id: "P002"
        idea: "業態PM、店舗マネージャー、スタッフの権限範囲"
        trigger: "フェーズ2開始時"
      - id: "P004"
        idea: "削除された商品の扱い"
        trigger: "運用開始後"
      - id: "P005"
        idea: "賞味期限管理、発注ロット"
        trigger: "必要になったら"
      - id: "P006"
        idea: "循環参照の登録時バリデーション"
        trigger: "問題が発生したら"
      - id: "P007"
        idea: "コースのセクション機能"
        trigger: "必要になったら"
      - id: "P008"
        idea: "リファクタリング Phase 4（UI操作の共通化）"
        trigger: "必要になったら"
      - id: "P009"
        idea: "メニューブック複数作成機能（大型店用/小型店用など）"
        trigger: "運用して必要になったら"
      - id: "P010"
        idea: "手書きメモの写真読み取り対応"
        trigger: "PPT/Excel/画像/PDFで運用が安定してから"
      - id: "P011"
        idea: "AIサポート：PPT/Excel対応"
        trigger: "画像/PDFで運用が安定してから"
        details: "Gemini APIが直接読めないため、テキスト抽出してから送る方式が必要"
      - id: "P012"
        idea: "items.js内の商品選択モーダルの共通化"
        trigger: "必要になったら"
        details: "F027で共通化したモーダル以外の候補"

  # =====================================
  # 3. 現在の進捗
  # =====================================
  progress:
    current_phase:
      step: "機能開発完了"
      name: "待機中"
      status: "idle"

    current_task:
      description: "実装中・計画中の機能なし。新しい機能の要望があれば対応。"

    next_tasks: []

  # =====================================
  # 4. ファイル構成
  # =====================================
  file_structure:
    tree: |
      project-root/
      ├── index.html           ← 仕入れ商品一覧（トップページ）
      ├── import.html          ← インポート画面
      ├── items.html           ← アイテム画面（手動単価UI追加）
      ├── preparations.html    ← 仕込み品画面（モーダルHTML削除済み）
      ├── dishes.html          ← 商品画面（モーダルHTML削除済み）
      ├── master.html          ← マスタ管理画面
      ├── courses.html         ← コース画面
      ├── menubook.html        ← メニューブック（閲覧専用）
      ├── recipebook.html      ← レシピブック（閲覧専用）
      ├── ai-support.html      ← AIサポート（セッション履歴追加）
      ├── vite.config.js
      ├── package.json
      ├── .env
      ├── prompt/
      │   ├── SYSTEM_PROMPT.yaml      ← AI振る舞い・汎用ルール
      │   ├── PROJECT_SPECIFIC.yaml   ← プロジェクト固有設定
      │   ├── ARCHITECTURE.yaml       ← 実装済み機能の仕様書
      │   ├── WORKFLOW.yaml           ← 進捗・決定事項
      │   └── DATABASE.md             ← テーブル定義
      ├── src/
      │   ├── main.js            ← 仕入れ商品一覧用JS
      │   ├── import.js          ← インポート用JS
      │   ├── items.js           ← アイテム用JS（手動単価対応完了）
      │   ├── preparations.js    ← 仕込み品用JS（modalManagers.js使用）
      │   ├── dishes.js          ← 商品用JS（modalManagers.js使用）
      │   ├── master.js          ← マスタ管理用JS
      │   ├── courses.js         ← コース用JS
      │   ├── menubook.js        ← メニューブック用JS
      │   ├── recipebook.js      ← レシピブック用JS
      │   ├── ai-support.js      ← AIサポート用JS（modalManagers.js使用）
      │   ├── costCalculator.js  ← 原価計算共通関数
      │   ├── businessType.js    ← 業態管理共通モジュール
      │   ├── utils.js           ← 共通ユーティリティ（モーダル以外）
      │   ├── modalManagers.js   ← モーダル管理クラス
      │   ├── supabase.js        ← Supabase接続
      │   └── style.css
      └── supabase/
          └── functions/
              ├── ai-read-recipe/      ← Edge Function（実装済み）
              │   ├── index.ts
              │   └── deno.json
              ├── ai-check-duplicates/ ← Edge Function（実装済み）
              │   └── index.ts
              └── ai-search-keywords/  ← Edge Function（実装済み）
                  └── index.ts

    files:
      # --- HTML ---
      - path: "index.html"
        purpose: "仕入れ商品一覧画面（トップページ）"
        imports: ["src/main.js"]
      - path: "import.html"
        purpose: "CSVインポート画面"
        imports: ["src/import.js"]
      - path: "items.html"
        purpose: "アイテム一覧・登録画面（手動単価UI追加）"
        imports: ["src/items.js"]
      - path: "preparations.html"
        purpose: "仕込み品一覧・登録画面（モーダルHTML削除済み）"
        imports: ["src/preparations.js"]
        note: "材料選択モーダル・クイックアイテムモーダルはJSで動的生成"
      - path: "dishes.html"
        purpose: "商品一覧・登録画面（モーダルHTML削除済み）"
        imports: ["src/dishes.js"]
        note: "材料選択モーダル・クイックアイテムモーダルはJSで動的生成"
      - path: "master.html"
        purpose: "マスタ管理画面"
        imports: ["src/master.js"]
      - path: "courses.html"
        purpose: "コース一覧・登録画面"
        imports: ["src/courses.js"]
      - path: "menubook.html"
        purpose: "メニューブック（商品閲覧専用）"
        imports: ["src/menubook.js"]
      - path: "recipebook.html"
        purpose: "レシピブック（仕込み品閲覧専用）"
        imports: ["src/recipebook.js"]
      - path: "ai-support.html"
        purpose: "AIサポート画面（セッション履歴追加）"
        imports: ["src/ai-support.js"]

      # --- JavaScript ---
      - path: "src/main.js"
        purpose: "仕入れ商品一覧のメインロジック"
        imports: ["src/supabase.js", "src/utils.js", "src/businessType.js"]
      - path: "src/import.js"
        purpose: "CSVインポートのロジック"
        imports: ["src/supabase.js", "src/utils.js"]
      - path: "src/items.js"
        purpose: "アイテム画面のロジック（手動単価対応完了）"
        imports: ["src/supabase.js", "src/costCalculator.js", "src/businessType.js", "src/utils.js"]
      - path: "src/preparations.js"
        purpose: "仕込み品画面のロジック"
        imports: ["src/supabase.js", "src/costCalculator.js", "src/businessType.js", "src/utils.js", "src/modalManagers.js"]
      - path: "src/dishes.js"
        purpose: "商品画面のロジック"
        imports: ["src/supabase.js", "src/costCalculator.js", "src/businessType.js", "src/utils.js", "src/modalManagers.js"]
      - path: "src/master.js"
        purpose: "マスタ管理画面のロジック"
        imports: ["src/supabase.js", "src/businessType.js"]
      - path: "src/courses.js"
        purpose: "コース画面のロジック"
        imports: ["src/supabase.js", "src/costCalculator.js", "src/businessType.js", "src/utils.js"]
      - path: "src/menubook.js"
        purpose: "メニューブック画面のロジック"
        imports: ["src/supabase.js", "src/costCalculator.js", "src/businessType.js", "src/utils.js"]
      - path: "src/recipebook.js"
        purpose: "レシピブック画面のロジック"
        imports: ["src/supabase.js", "src/costCalculator.js", "src/businessType.js", "src/utils.js"]
      - path: "src/ai-support.js"
        purpose: "AIサポート画面のロジック"
        imports: ["src/supabase.js", "src/costCalculator.js", "src/businessType.js", "src/utils.js", "src/modalManagers.js"]
        features:
          - "ファイルアップロード（画像/PDF）"
          - "Edge Function呼び出し（ai-read-recipe, ai-check-duplicates, ai-search-keywords）"
          - "7ステップのウィザードUI"
          - "紐付けモーダル"
          - "クイックアイテム作成モーダル（modalManagers.js使用）"
          - "AI類似チェック"
          - "AIキーワード検索"
          - "セッション自動保存・復元"
          - "履歴一覧UI"
          - "「仕入れ商品なしで作成」ボタン"

      # --- 共通モジュール ---
      - path: "src/costCalculator.js"
        purpose: "原価計算の共通関数（手動単価対応完了）"
        exports:
          - "calculateItemUnitCost"
          - "calculatePreparationCost"
          - "calculateDishCost"
          - "getIngredientUnitCost"
      - path: "src/businessType.js"
        purpose: "業態管理の共通モジュール"
        exports:
          - "initBusinessTypeSelector"
          - "getCurrentBusinessTypeId"
          - "setCurrentBusinessTypeId"
          - "clearBusinessTypesCache"
      - path: "src/utils.js"
        purpose: "共通ユーティリティ関数（モーダル以外）"
        exports:
          - "toHalfWidthKatakana"
          - "toFullWidthKatakana"
          - "sanitizeToFullWidthKatakana"
          - "normalizeForSearch"
          - "getIngredientName"
          - "getIngredientUnit"
          - "prepHasNeedsReviewIngredient"
          - "dishHasNeedsReviewIngredient"
          - "getNeedsReviewIngredientList"
          - "loadTaxRate"
          - "readFileAsShiftJIS"
          - "parseCSV"
          - "findColumnIndex"
          - "fetchAllWithPaging"
          - "withBusinessTypeFilter"
          - "renderIngredientList"
          - "renderIngredientTree"
      - path: "src/modalManagers.js"
        purpose: "モーダル管理クラス"
        exports:
          - "IngredientModalManager"
          - "QuickItemModalManager"
        note: "HTML動的生成、DOM/Object両対応のopen()メソッド"
      - path: "src/supabase.js"
        purpose: "Supabase接続設定"
        exports: ["supabase"]

      # --- Edge Functions ---
      - path: "supabase/functions/ai-read-recipe/index.ts"
        purpose: "Gemini APIを呼び出してレシピを読み取るEdge Function"
      - path: "supabase/functions/ai-check-duplicates/index.ts"
        purpose: "AI類似判定Edge Function"
      - path: "supabase/functions/ai-search-keywords/index.ts"
        purpose: "AIキーワード生成Edge Function"

      # --- ドキュメント ---
      - path: "prompt/SYSTEM_PROMPT.yaml"
        purpose: "AI振る舞い・汎用ルール（全プロジェクト共通）"
      - path: "prompt/PROJECT_SPECIFIC.yaml"
        purpose: "プロジェクト固有の設定・仕様"
      - path: "prompt/ARCHITECTURE.yaml"
        purpose: "実装済み機能の仕様書"
      - path: "prompt/WORKFLOW.yaml"
        purpose: "進捗・決定事項・ファイル構成"
      - path: "prompt/DATABASE.md"
        purpose: "データベース設計ドキュメント"

  # =====================================
  # 5. 注意点・ハマったこと
  # =====================================
  cautions:
    reminders:
      - "DBに変更を加えたらDATABASE.mdを更新する"
      - "1000件超えるテーブルはfetchAllWithPaging()を使う"
      - "TailwindCSS v4で任意値が効かない場合はインラインスタイル"
      - "新しい画面を追加したら全HTMLのサイドメニューを更新"
      - "読み仮名の制限はinputではなくblurイベントで行う"
      - "原価計算はcostCalculator.jsの共通関数を使う（DBには保存しない）"
      - "業態関連のデータ登録時はgetCurrentBusinessTypeId()で業態IDを取得"
      - "業態フィルタはwithBusinessTypeFilter()を使う"
      - "全業態共通の項目を変更する際は確認メッセージを出す"
      - "Edge Functionデプロイ後はJWT認証設定を確認（OFFにする）"
      - "Gemini APIのthinkingConfigはgenerationConfig内に配置"
      - "Edge Functionのモデル名はgemini-2.5-flashを使用"
      - "手動単価アイテムはyield_quantityに総量、manual_unit_costに計算後の単位原価を保存"
      - "機能が完了したらARCHITECTURE.yamlに移動すること"
      - "QuickItemModalManagerはcreateModal()を呼んでからopenする（HTMLが動的生成されるため）"
      - "QuickItemModalManager.open()はDOM要素とオブジェクト両方に対応（instanceof HTMLElementで判定）"
      - "モーダル共通化は要件定義から丁寧に進めること（影響範囲が大きい）"
      - "モーダル管理クラスはmodalManagers.jsに集約、utils.jsには入れない"